== Debugger
=== Terminal handling

==== Linux
===== Mint Linux
Standard way is currently to use gnome terminal in such way (under the hood)
----
bash -c x-terminal-emulator -e bash --login -c 'cd /tmp/xyz;./terminallaunchXYZ.sh -a 1 -b 2;_exit_status=$?;echo "XYZ"'
----
===== CentOS
With https://github.com/de-jcup/eclipse-bash-editor/issues/150 a problem
come up with cent OS: The terminal was not launchable out of the box

===== More common way
There must be a possibility to define a custom approach but still preventing users to make things wrong... or have to change every time the call.
 
====== Potential solution
Provide the complete execution string and define a variable
which represents the script to launch.

For example:
----
bash -c x-terminal-emulator -e bash --login -c 'cd ${EBE_TMP_FOLDER};./${EBE_SCRIPTNAME} -a 1 -b 2;_exit_status=$?;echo "XYZ"'
----

or (maybe better):
----
bash -c x-terminal-emulator -e bash --login -c '${BE_CMD_CALL}'
----


==== Windows
===== Win 7
====== GIT for windows (MinGW)
Win7 with installed `GIT for windows` comes up with a MinGW and the 
defaults are working good
----
 cmd.exe /C start "Bash Editor DEBUG Session: test.sh" cmd.exe /C "bash --login -c './test.sh ;_exit_status=$?;echo "Exit code=$_exit_status";read -p "Press enter to continue..."'"
----

reduced:

----
 cmd.exe /C start "${BE_CMD_TITLE}" cmd.exe /C "bash --login -c '${BE_CMD_CALL}'
----


===== Win 10
====== WSL
There are problems with the handling, see 
https://github.com/de-jcup/eclipse-bash-editor/issues/155 for details.

====== Solution WSL and other systems on windows

ditaa::diagrams/wsdl-solution.ditaa[] 



=== General approach
- Use a new preference id for the terminal command (so no migration necessary)
- Default becomes system specific, so pressing `Restore Defaults` will bring up
  os relevant standard which is currently working for win7 and Linux Mint/Ubuntu
- Should be inside a bigger Textfield (like done for AsciiDoctor-Editor) and
  separate whitespaces to command parts.
- There should be an option `Show resulting call` near `Test` button, so 
  user can check the output before executing... The build command should
  be shown in a text box where users can copy it.


